name: Rehydrate Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  rehydrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform-microservice

    - name: Validate Terraform
      run: terraform validate
      working-directory: terraform-microservice

    - name: Plan Terraform
      run: terraform plan -out=tfplan
      working-directory: terraform-microservice

    - name: Apply Terraform
      if: github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
      working-directory: terraform-microservice

    - name: Echo done message
      run: echo "done!"